mysql:
  container_name: "mysql"
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
  ports:
    - "3306:3306"
  volumes:
    - "~/Project:/Project"

gcp:
  container_name: "gcp"
  image: ubuntu:trusty
  ports:
    - "8080:8080"
    - "8000:8000"
  volumes:
      - "~/Project:/Project"
  links:
    - mysql:mysql
  tty: true

ubuntu:
  container_name: "ubuntu"
  image: ubuntu
  ports:
    - "3000:3000"
    - "8081:8080"
    - "8001:8000"
  volumes:
    - "~/Project:/Project"
  links:
    - mysql:mysql
  tty: true
